### ISSUE TITLE
Create a DistGit 

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/console-operator#1]
Following https://jira.coreos.com/browse/ART-85 we need a DistGit created for the Console Operator.  

Completing the above includes items like:
- https://github.com/jupierce/enterprise-images-upstream-example

**Comment by benjaminapetersen** [comment]
https://jira.coreos.com/browse/ART-177

**Comment by benjaminapetersen** [comment]
@adammhaile for reference.

**Comment by adammhaile** [comment]
@markllama FYI

**Comment by benjaminapetersen** [comment]
@markllama FYI

**Comment by benjaminapetersen** [comment]
@markllama curious if there has been any movement on this, thanks!

**Comment by markllama** [comment]
I haven't seen any of this because it's tracked int he Jira ticket where I currently have 20 others pending.  
Currently still waiting for ack that a dist-git exists.  Can you paste the RCM ticket URL into the jira ticket?

**Comment by benjaminapetersen** [comment]
Migrating this to Jira:
https://jira.coreos.com/browse/CONSOLE-950
