### ISSUE TITLE
CRD and CR for operator resource config need to be updated to guidelines

### ISSUE THREAD

**Issue by enj** [openshift/console-operator#105]
See https://docs.google.com/document/d/1aIIFMRpzfNh_sOAMf2NQ2iXUD5AeUYgWZNEhiqTwyYE and 
https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/manifests/0000_10_kube-apiserver-operator_01_config.crd.yaml as an example.

**Comment by spadgett** [comment]
@benjaminapetersen @enj anything left for this?

**Comment by benjaminapetersen** [comment]
Well, this document hasn't really been kept up to date.  There are a couple things that could still be done:

- `Force ManagementState = "Force"` - I'm not 100% certain [this](https://github.com/openshift/api/blob/master/operator/v1/types.go#L32) does much for us. 
- `OperatorSpec.LogLevel` - We have talked about doing [this](https://github.com/openshift/api/blob/master/operator/v1/types.go#L55), it needs to be piped down into the operand/console. 
- `OperatorSpec.ObservedConfig` - Essentially, we need 2 sync loops. 
 The first for top level config, operator config, etc.  We should collect & build our config, then merge`upsupportedConfigOverrides`, and then publish the merged config here.  THEN we should have a separate sync loop watching for just this update & applying the merged config to our resources.  [This](https://github.com/openshift/api/blob/master/operator/v1/types.go#L74).  Its a decent bit of work splitting up our sync loop just to get back to where we are at.  I don't know if any other operators support this yet.
- `OperatorSpec.OperandSpecs` - If useful, this provides [another layer of overrides](https://github.com/openshift/api/blob/master/operator/v1/types.go#L103).

**Comment by benjaminapetersen** [comment]
I'm closing this as I've broken it out into issues in Jira in the [Console Operator Epic](https://jira.coreos.com/secure/RapidBoard.jspa?rapidView=134&projectKey=CONSOLE&view=planning.nodetail&selectedIssue=CONSOLE-1322&epics=visible&selectedEpic=PROD-667).
