### ISSUE TITLE
Tech Debt: Investigate shell script cleanup

### ISSUE THREAD

**Issue by enj** [openshift/console-operator#106]
Note how https://github.com/openshift/cluster-kube-apiserver-operator does not have a pile of shell scripts, probably because they have some new Makefile magic in library-go (https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/Makefile).

**Comment by benjaminapetersen** [comment]
migrated
https://jira.coreos.com/browse/CONSOLE-1376
