### ISSUE TITLE
Update namespaces

### ISSUE THREAD

**Issue by enj** [openshift/console-operator#108]
See aos-devel thread.  At the very least you need to split out the namespace for operator and operand.

**Comment by spadgett** [comment]
We've previously raised this with @jwforres and @derekwaynecarr. They said it wasn't a priority for 4.0, and we can reevaluate in a later release.

/close
for now

**Comment by enj** [comment]
How will you know to reevaluate without a bug or issue tracking it?

**Comment by spadgett** [comment]
It should be tracked in JIRA since it's what we use for planning.

CONSOLE-1206

**Comment by spadgett** [comment]
This work was completed in #116
