### ISSUE TITLE
is it possible to add "app Item" to Catalog???

### ISSUE THREAD

**Issue by angry-tony** [openshift/console-operator#215]
Hello! all..

is there way to add "customized Item"  and see it on "Developer Catalog" in Openshift 4??
( openshift 3 can do it using "ASB + APB + local registry" )

**like below...**
![image](https://user-images.githubusercontent.com/18000837/56705270-3f141680-674b-11e9-9ebf-9dc2e503461d.png)

**Comment by benjaminapetersen** [comment]
@angry-tony there are several extensions coming to the console in the near future.  You can read the CRDs for these here:
https://github.com/openshift/console-operator/tree/master/manifests
- console-link
- console-cli-download
- console-log-link
- console-notification

You can also go look at the Console github repo for the corresponding PRs that enable these features in the console to see if they do what you are desiring to do:
https://github.com/openshift/console/pull/1776

But specifically for the catalog, there is not an extension currently for the catalog.

**Comment by spadgett** [comment]
@angry-tony We support Ansible Service Broker in OpenShift 4.1 as well, so you should be able to do it the same way as before.
