### ISSUE TITLE
Using Custom (Valid) SSL Cert with Console

### ISSUE THREAD

**Issue by sclarkso** [openshift/console-operator#217]
I have tried these commands to use a custom (letsencrypt) ssl cert for the console:

```
$ oc create secret tls new-cert --cert=server.crt --key=server.key -n openshift-ingress

$ oc patch ingresscontroller.operator default --type=merge -p "{\"spec\":{\"defaultCertificate\":{\"name\": \"new-cert\"}}}" -n openshift-ingress-operator
```

This results in a seemingly valid cert for the console, at least for the log in page.  However once you log in, this is what you get instead of the console:

![image](https://user-images.githubusercontent.com/22138473/56984120-48d6b900-6b53-11e9-929d-0aeddbbb2d2d.png)

I have tried deleting the openshift-authentication pods, and the console pods.  The console pods will not come back up and have this error in the logs:
```
2019/04/30 17:55:41 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://openshift-authentication-openshift-authentication.apps.sclarkso.openshift.redhatkeynote.com/oauth/token failed: Head https://openshift-authentication-openshift-authentication.apps.sclarkso.openshift.redhatkeynote.com: x509: certificate signed by unknown authority
2019/04/30 17:55:51 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://openshift-authentication-openshift-authentication.apps.sclarkso.openshift.redhatkeynote.com/oauth/token failed: Head https://openshift-authentication-openshift-authentication.apps.sclarkso.openshift.redhatkeynote.com: x509: certificate signed by unknown authority
2019/04/30 17:56:01 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://openshift-authentication-openshift-authentication.apps.sclarkso.openshift.redhatkeynote.com/oauth/token failed: Head https://openshift-authentication-openshift-authentication.apps.sclarkso.openshift.redhatkeynote.com: x509: certificate signed by unknown authority
```

**Comment by eyenx** [comment]
bump - we have the same issue.

**Comment by eyenx** [comment]
@sclarkso look at this : https://access.redhat.com/solutions/4245561

**Comment by spadgett** [comment]
This looks like it's related to https://bugzilla.redhat.com/show_bug.cgi?id=1712525 although I would expect letsencrypt certs to just work. We include system roots when talking to the OAuth server. If you ssh into to the pod, do you see errors if you curl the OAuth server?

The JSON response from the original description is a different error that has since been fixed: https://bugzilla.redhat.com/show_bug.cgi?id=1686476

cc @enj

**Comment by benjaminapetersen** [comment]
I'll mirror this in Jira so we can prioritize.

**Comment by benjaminapetersen** [comment]
Created in JIRA:
https://jira.coreos.com/browse/CONSOLE-1649

Closing here so we can work off of that.
