### ISSUE TITLE
Check if this crashes the operator

### ISSUE THREAD

**Issue by enj** [openshift/console-operator#29]
Pick any resource that your operator watches, run your operator, create lots of said resource, delete all of them, repeat for a bit while watching the operator logs

/assign @benjaminapetersen

**Comment by benjaminapetersen** [comment]
what do you expect the logs to say?  :D 

other than "boom"

**Comment by enj** [comment]
I expect a panic or, if you get really lucky, nothing.

**Comment by benjaminapetersen** [comment]
no longer SDK.
