### ISSUE TITLE
Why did the console port change from OpenShift4?

### ISSUE THREAD

**Issue by Daiki-Kawanuma** [openshift/console-operator#401]
Hi,

In OpenShift 3, we could access OpenShift Console on port 8443.
But in OpenShift 4, the console port seems to have changed to 443.

This means end user and administrator use same traffic route and I think it is unsuitable in the perspective of security and network.

What is the intention of this change?
Can I change the port like OpenShift 3?

**Comment by duritong** [comment]
You can always move the application routes to a different router-shard.

The console is just another application on OCP (instead hooked into the API), so it also uses all the standard mechanisms to expose itself.
