### ISSUE TITLE
rename /deploy/cr.yaml to /examples/cr.yaml, move some existing to /manifests

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/console-operator#45]
- `/deploy` could be JUST the `cr.yaml`
- `/manifests` can be all the things for install.  that or `/examples`?

the `cr.yaml` is different than the rest.

**Comment by benjaminapetersen** [comment]
`/bootstrap` is just for `cr.yaml`.  if `console` doesn't exist, read from disk and create, is the console`operator`s first action.

**Comment by benjaminapetersen** [comment]
That or just create it in `golang`.

**Comment by benjaminapetersen** [comment]
I'm leaning toward doing this in `golang` code`, but moving the `cr.yaml` instead to a `/examples` folder.

**Comment by hongkailiu** [comment]
Hi @benjaminapetersen 
Probably this is WIP.
The steps in `README.md` are currently broken since the files, e.g., `operator.yaml` in `deploy` folder is renamed/moved.
Should we fix it too?
Thanks.

**Comment by benjaminapetersen** [comment]
@hongkailiu thx, I will update!

**Comment by benjaminapetersen** [comment]
@hongkailiu PR #48 will update the readme (much more simple).

**Comment by hongkailiu** [comment]
@benjaminapetersen Thanks.
PR Watched.

**Comment by benjaminapetersen** [comment]
This issue is done.

We updated README.md earlier, I may have to update it again soon.  There is a PR open right now that will cause the `operator` to automatically create a `console` when deployed if a `console` does not exist, eliminating one step.  Will wait until that lands before another README refresh.

**Comment by hongkailiu** [comment]
@benjaminapetersen 
Could you please add the link of the open PR?
I would like to resume my test after the README.md is done when that PR is also merged. Thanks.

**Comment by hongkailiu** [comment]
Found and watched it. https://github.com/openshift/console-operator/pull/60
