### ISSUE TITLE
Unable to add whitelist annotation to cli downloads route

### ISSUE THREAD

**Issue by stujb** [openshift/console-operator#632]
We would like to be able to restrict by IP access to the downloads route in the openshift-console project using the ip whitelist annotation.

This currently does not appear possible as any update to add the required annotation is reverted by the console-operator

**Comment by jhadvig** [comment]
Hey @stujb. Thanks for reporting this issue! I've ported it to our Jira, so we can prioritise and size the work.

Here is the link: https://issues.redhat.com/browse/CONSOLE-3054

Closing the issue since it will be tracked in Jira.
