### ISSUE TITLE
Update if err != nil statements to return context(err) 

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/console-operator#8]
Returning context(err) will give much better error messages via a stack trace. Do this.

**Comment by enj** [comment]
I think you confused `context.Context` with the concept of adding contextual information.  See https://commandcenter.blogspot.com/2017/12/error-handling-in-upspin.html and https://dave.cheney.net/2016/06/12/stack-traces-and-the-errors-package as examples for what I was referring to.

**Comment by benjaminapetersen** [comment]
obsolete.

**Comment by enj** [comment]
> obsolete.

How?

**Comment by benjaminapetersen** [comment]
Hold on, perhaps not. i'll re-open. was closing off a bunch of stuff related to SDK, etc.
